### ISSUE TITLE
Inactive Descriptions show up in search

### ISSUE THREAD

**Issue by sidharthramesh** [wardle/hermes#41]
Indexed: SnomedCT_InternationalRF2_PRODUCTION_20220930T120000Z
Version: 1.0.712
Server is running

### Problem
The search results seem to return the same term multiple times. For example, searching "Paracetamol 500", returns an array with "Paracetamol 500mg tablet", and "Paracetamol 500mg tablet" as the first 2 results, both belonging to the concept 322236009.

```
curl http://localhost:8080/v1/snomed/search?s=paracetamol%20500
```

```json
[
	{
		"id": 464271012,
		"conceptId": 322236009,
		"term": "Paracetamol 500mg tablet",
		"preferredTerm": "Paracetamol 500 mg oral tablet"
	},
	{
		"id": 1236200010,
		"conceptId": 322236009,
		"term": "Paracetamol 500mg tablet",
		"preferredTerm": "Paracetamol 500 mg oral tablet"
	},
	{
		"id": 464300011,
		"conceptId": 322280009,
		"term": "Paracetamol 500mg capsule",
		"preferredTerm": "Paracetamol 500 mg oral capsule"
	},
	{
		"id": 1236213016,
		"conceptId": 322280009,
		"term": "Paracetamol 500mg capsule",
		"preferredTerm": "Paracetamol 500 mg oral capsule"
	},
	{
		"id": 2154521017,
		"conceptId": 322280009,
		"term": "Paracetamol 500mg capsule",
		"preferredTerm": "Paracetamol 500 mg oral capsule"
	},
	{
		"id": 464283014,
		"conceptId": 322250004,
		"term": "Paracetamol 500mg suppository",
		"preferredTerm": "Paracetamol 500 mg rectal suppository"
	},
	{
		"id": 1236205017,
		"conceptId": 322250004,
		"term": "Paracetamol 500mg suppository",
		"preferredTerm": "Paracetamol 500 mg rectal suppository"
	}
]
```

Investigating the descriptions:

```
curl http://localhost:8080/v1/snomed/concepts/322236009/extended | jq ".descriptions[] | select (.active)"
```
```json
{
  "id": 3500544012,
  "effectiveTime": "2017-07-31",
  "active": true,
  "moduleId": 900000000000207000,
  "conceptId": 322236009,
  "languageCode": "en",
  "typeId": 900000000000013000,
  "term": "Acetaminophen 500 mg oral tablet",
  "caseSignificanceId": 900000000000448000,
  "refsets": [
    900000000000509000,
    900000000000508000
  ],
  "preferredIn": [
    900000000000509000
  ],
  "acceptableIn": [
    900000000000508000
  ]
}
{
  "id": 3500545013,
  "effectiveTime": "2017-07-31",
  "active": true,
  "moduleId": 900000000000207000,
  "conceptId": 322236009,
  "languageCode": "en",
  "typeId": 900000000000013000,
  "term": "Paracetamol 500 mg oral tablet",
  "caseSignificanceId": 900000000000448000,
  "refsets": [
    900000000000509000,
    900000000000508000
  ],
  "preferredIn": [
    900000000000508000
  ],
  "acceptableIn": [
    900000000000509000
  ]
}
{
  "id": 3681734015,
  "effectiveTime": "2018-07-31",
  "active": true,
  "moduleId": 900000000000207000,
  "conceptId": 322236009,
  "languageCode": "en",
  "typeId": 900000000000003000,
  "term": "Product containing precisely paracetamol 500 milligram/1 each conventional release oral tablet (clinical drug)",
  "caseSignificanceId": 900000000000448000,
  "refsets": [
    900000000000509000,
    900000000000508000
  ],
  "preferredIn": [
    900000000000509000,
    900000000000508000
  ],
  "acceptableIn": []
}
```

Only 3 active descriptions are found. The description with id 464271012 is not active, however, it's being shown in the search results.

**Expected:** Only active concepts should show up by default.

**Comment by sidharthramesh** [comment]
Or there should be a way to only search for active descriptions

**Comment by wardle** [comment]
Thanks Sidharth. Yes you can simply ask to omit inactive descriptions. There are flags to search inactive concepts (default false) and inactive descriptions (default true) already. 

But actually that would be a mistake because there are inactive descriptions that should be searchable eg Wegeners. Not being able to find those will be annoying to end users. 

So the issue is that it appears there are inactive descriptions with exactly the same term as either the active description or other inactive descriptions. That means it looks as if there are duplicates. 

The options are

Do nothing : because it doesn't matter - record whatever concept is they choose and carry on. 

Filter duplicate terms (the text) in the UI - it actually doesn't matter which of the duplicates you keep as long as the concept ids match, unless you are also storing the chosen description id. 

Filter inactive duplicate terms in the service so that items are removed if the text matches an active description of the same concept.

This didn't used to be a problem at all, but it looks as if it is a bigger problem now as there has been churn in activating new descriptions and deactivated old descriptions. I don't know why this has happened if the terms are the same but obviously that is an upstream issue. 

I wonder how other servers handle this?

Also if we were to add this filter at the API/server level, then it would need to default to off in line with non breaking change policy, so one would need to opt-in to get more filtered results.

**Comment by wardle** [comment]
I think the best approach would be to add a 'hide duplicate inactive descriptions' flag which would simply remove any inactive descriptions with the same term as an active description in the same set of results.

**Comment by sidharthramesh** [comment]
I think that flag makes a lot of sense. Hiding duplicate inactivated concepts seems to be the best approach - maybe set this flag to true by default, but can be overridden using a query param?

**Comment by wardle** [comment]
It has to be additive so that there are no breaking changes. There will be code that uses search that expects a certain behaviour, and this would be a change in behaviour, so this would have to be opt-in, at least at the underlying service level, or a new endpoint with different defaults. This code is used everywhere in my EPR applications and analytics pipelines for a variety of purposes, so breaking changes are a definite no-go.

Options for the flag:

1. remove-duplicates

Duplicate results are removed based on description 'term' and 'conceptId'. This may remove the actual active description. Pros: very simple to implement. Cons: inactive descriptions might be returned instead of active descriptions, but that doesn't matter for most (all?) cases as the concept ids would be the same. This is a server-side implementation of the logic described above in the UI. 

2. remove-inactive-duplicates

Indexed fields can either be stored or not stored. At the moment, I do not store whether the concept or description is active, even though they are indexed and available for search. That means that, at the moment, the 'active' flag for either the related concept or the description itself, are not returned in the results. So, there is no current way of, at the point of returning results, to filter out duplicate items by looking at conceptId, description term and the description 'active' flag. In order to do this, I'd have to _store_ the active flag(s). Pros: this is still very simple to implement. Cons: We have to modify the index schema and bump versions for compatibility.

The only reason for favouring (2) is if clients need to get the descriptionId of the chosen term. I never use this information, storing only the conceptId after a user chooses a term, or for other non-supervised uses, the first match.

So do you use the returned descriptionId at all, or only use the conceptId?

**Comment by sidharthramesh** [comment]
I completely understand the point about maintaining backward compatibility.

I don't use the description ID for my use cases either. And solution 1 should be fine for me personally. However, I think solution 2 is probably more future-proof. What if another user wants to store the descriptions?

Regarding how other servers do it, I can take you through SnowOwl's API (not the best / straightforward in my opinion):
They have a concept and a description endpoint:
The concept endpoint takes an active:boolean query parameter to only show the active concepts. For descriptions, one has to set the expand parameter to "descriptions()". They have more complex expression in the exmand parameter to filter and sort descriptions as well. Eg: expand: fsn(),pt(),descriptions() shows all the fsn, preferred term and descriptions in the concept result.

You could also search the descriptions API, set active=true, and then expand: concept(expand(fsn())) - this will return the concept's fsn along with each description.

They have a cool Swagger UI as well:
![image](https://user-images.githubusercontent.com/18082719/195976558-e0d3e407-4202-4a6d-985d-9f90b2111ce5.png)

Very feature-rich, but the most obvious kind of search is not the default like in Hermes. And Hermes tends to perform much better as well. So I use SnowOwl to author new concepts, export the RF2 file, index it using Hermes and use that container image to deploy quick searches.

**Comment by wardle** [comment]
The underlying Hermes search supports flags to alter the search - including whether to include or exclude inactive concepts and inactive descriptions or any combination. But I have just noticed that I haven't made these flags available at the REST API level. So I will sort that (it is very trivial). 

I think there is always the option for clients to manage this duplicate terms issue themselves, so that rather than increasing index size and potentially causing versioning issues, for a use case not actually used, my initial thought is to simply filter out duplicates in a naive way. 

I will ponder on this for little time to think through the options and the pros and cons.

**Comment by wardle** [comment]
As an aside, you don't need to go through the contortions with `jq`  - you can HTTP GET at /v1/snomed/concepts/322236009/descriptions and get descriptions for a given concept. See [API endpoints in source code ](https://github.com/wardle/hermes/blob/83d32db15ecd3220ed35fde6473d68ebb72226af/cmd/com/eldrix/hermes/cmd/server.clj#L227)

**Comment by wardle** [comment]
Both the internal API, and the HTTP REST API now have a flag to remove consecutive duplicates, based upon having identical concept identifiers and description terms. For example use removeDuplicates=1 at the HTTP API level.

**Comment by wardle** [comment]
The additional options for search, such as whether to include or exclude inactive concepts and descriptions, as well as a new option to remove duplicates in auto completion, are in today's release.

**Comment by sidharthramesh** [comment]
Thank you! I'll try out the latest release.

**Comment by wardle** [comment]
More documentation added in 8617ba1d2c4fca48f2768197b01e5defe4c2f30f ; see [README](https://github.com/wardle/hermes#search)
