### ISSUE TITLE
Build from source - ClassNotFoundException

### ISSUE THREAD

**Issue by freshehr** [wardle/hermes#51]
ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:445) when building from source.

Same on Ubuntu

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.10.2)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.10.2, mixed mode, sharing)

Macos

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

**Comment by wardle** [comment]
Hi. Sorry, current HEAD requires an additional compile step

```shell
clj -T:build compile-java
```

This is because I merged some Java source files into the codebase. When used as a library, Clojure tools support automatically 'prepping' a library by performing any specific build steps, but I was surprised that this doesn't happen when used like this. As such, I'll fix this in a few moments, by reverting this change.
