### ISSUE TITLE
Modify search to use normalised / folded strings to better handle diacritics

### ISSUE THREAD

**Issue by rlustemberg** [wardle/hermes#55]
Hi Mark,

Firstly, thank you for your continuous efforts with the Hermes terminology server. We've noticed a slight challenge when searching for specific Spanish SNOMED terms. After some investigation, we believe there's a possibility that the way Lucene (integrated within Hermes) processes Spanish terms might need some attention.

### Details

- We're primarily using the SNOMED Spanish AR edition.
- A search for 'nódulo hepático' using substrings like 'nod hep' doesn't return the anticipated results. Interestingly, when we use 'nód hep', the search is spot on.
- Given the integral role of Lucene in Hermes's search capabilities, there might be nuances related to Lucene's processing of Spanish terms.

To elaborate, if Lucene's default configurations (like tokenization, stemming, and stop words) are more English-centric, it could potentially lead to some nuances in handling Spanish terms within Hermes.

We genuinely appreciate any insights or suggestions you might have on this. Thank you for your understanding and support.

Best regards,

BTW: atm we're using hermes-1.2.1032

**Comment by wardle** [comment]
Hi. 

Yes I see the issue. Diacritics should be normalised to permit search except where they have significance. 

For Spanish I understand no diacritic characters are significant. As such, the index, or the search, should handle normalisation/folding. For other languages this isn't the case. 

I see snowstorm handles this with a master configuration - see https://github.com/IHTSDO/snowstorm/blob/5303ee10a1320f4febe992f460cb903ad6700494/src/main/resources/application.properties#L360

I would have to look at Lucene and see whether it can handle in a less manual manner. 

But are you using fuzzy search or fallback fuzzy? Because that should allow one or two characters to be incorrect anyway and therefore still allow your auto completion to work properly, irrespective of the diacritic characters?

**Comment by wardle** [comment]
The options are:

- Do nothing and use fuzzy search or fallback fuzzy search. 
- Use Lucene to normalise, but there would be issues with using different analysers for different documents. Different analysers are permitted on a per field basis but  we will have documents with different locales. 
- Add new search field with normalised text (when appropriate depending on language) not stored but only for search and use that for search. Whether that is default could be a function of whether there are languages installed with significant diacritics that should not be normalised. 

The key here is to avoid surprising behaviour. In some languages, it is surprising that searching for a doesn't match á. In other languages it would be surprising the other way around. 

Adding a new field would increase index size but it is a simple change. 

Then the issue is proper normalisation. The nice thing with manually managing this is that different approaches could be used depending on language and its rules. A simple regex replacement or Java has a built-in text normaliser. 

The normalisation for indexing and normalisation of search terms can of course then be tested independently of Lucene, and tested on a per-language basis according to preset rules. Lucene would happily index and search normalised text. 

Do we have to keep a non-normalised field? Yes. We have to keep an unadulterated (and stored) field for the original term for proper results reporting in search  and not having to look up original text in some other index which would be much slower than storing in each document.

**Comment by rlustemberg** [comment]
Hi Mark, we are using fallback fuzzy. We've just rebuild the db and tested using the latest version. The fuzzy search is still not handling letters with diacritics as similar to without diacritics. In Spanish, just normalising the indexes and making them insensitive to diacritics should not cause any trouble, afaik. Otherwise using a more complex fuzzy algorithm should probably be the way to go.

**Comment by rlustemberg** [comment]
Sounds good. Just to add more background information. Indeed, how languages handle diacritics is indeed a tricky matter. Even in Spanish, which only uses 3 diacritics (´, ¨, ˜), the rules are sort of fuzzy. In all cases the effect is phonetic, in a few cases semantic. The acute accent ( ´) has some times a semantic effect but can be minimised by the context. It's very common to make typos where we forget to type or write the accent. The tilde and umlaut have the most semantic effect, but it doesn't cause much confusion. Usually the word missing either the tilde or umlaut don't exists or has the same meaning.

It would be great to have a manual configuration for handling this. Indeed that seems to be the case in Snowstorm, where with the proper configuration we can handle diacritics in Spanish in a usable if not perfect way.

**Comment by wardle** [comment]
The other consideration is that distributions could (and should?) provide semantically equivalent synonyms - eg in the UK edition, Sjogren's has synonyms with and without diacritics. This is perhaps a more "correct" approach, as each concept can and should have the "semantically equivalent synonyms" which are meaningful in that language/distribution. 

It is quite clear that a simple normalisation would be fine for UK and Spain, but there are edge cases for other languages in which the semantics are quite different when diacritics are used, and that it would be the wrong behaviour to normalise without careful management.

**Comment by wardle** [comment]
Raised as an issue with SNOMED as issue no. 46373. Does not preclude a 'pluggable' normalisation strategy on a per-distribution / country-code basis and for opt-in during search, but some changes and complexity brought in to the way indexing and search occurs. This cannot be handled by a simple Lucene configuration change, unless that is configurable on startup so that normalisation occurs routinely in indexing for a given implementation. I'm less inclined on latter, as it adds deployment complexity and makes a given instance of Hermes locked to a given normalisation implementation rather than switching on a case-by-case basis, for example, when a given instance has had multiple distributions loaded which may require different rules.

**Comment by wardle** [comment]
Text folding has been added in branch https://github.com/wardle/hermes/tree/term-folding - this is experimental and for evaluation only
